# Generated by Django 4.2 on 2024-11-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts', '0009_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_arts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_likes', to='arts.art'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
